package qdata

const (
	FTAreasOfResponsibilities FieldType = "AreasOfResponsibilities"
	FTChildren                FieldType = "Children"
	FTDescription             FieldType = "Description"
	FTEmail                   FieldType = "Email"
	FTEntityCreated           FieldType = "EntityCreated"
	FTEntityDeleted           FieldType = "EntityDeleted"
	FTFirstName               FieldType = "FirstName"
	FTIsEmailVerified         FieldType = "IsEmailVerified"
	FTIsEnabled               FieldType = "IsEnabled"
	FTJSON                    FieldType = "JSON"
	FTKeycloakId              FieldType = "KeycloakId"
	FTLastEventTime           FieldType = "LastEventTime"
	FTLastName                FieldType = "LastName"
	FTLogLevel                FieldType = "LogLevel"
	FTLogout                  FieldType = "Logout"
	FTName                    FieldType = "Name"
	FTParent                  FieldType = "Parent"
	FTQLibLogLevel            FieldType = "QLibLogLevel"
	FTRoles                   FieldType = "Roles"
	FTSchemaChanged           FieldType = "SchemaChanged"
	FTSourceOfTruth           FieldType = "SourceOfTruth"
)
