#!/bin/bash

# Convert JavaScript code in web/ to Go web handlers

# Define the web directory path
JS_DIR="pkg/web/js"

# Loop through each JavaScript file in the web directory
for FILE in $(find $JS_DIR -type f -name "*.js"); do
    # Extract the file name without extension
    FILENAME=$(basename $FILE .js)
    CONTENT=$(cat $FILE | sed 's/`/` + "`" + `/g')
    
    # Define the output file path
    OUTPUT_FILE="pkg/web/go/autogen_handler_$FILENAME.go"

    # Create the output file
    echo "// THIS IS AN AUTOGENERATED FILE... See gen_web_handlers.sh for details." > $OUTPUT_FILE
    echo "package web" >> $OUTPUT_FILE
    echo "" >> $OUTPUT_FILE
    echo "import (" >> $OUTPUT_FILE
    echo "    \"net/http\"" >> $OUTPUT_FILE
    echo "    \"fmt\"" >> $OUTPUT_FILE
    echo ")" >> $OUTPUT_FILE
    echo "" >> $OUTPUT_FILE
    echo "func Register_web_handler_$FILENAME() {" >> $OUTPUT_FILE

    # Convert the JavaScript code to a Go web handler function
    echo "" >> $OUTPUT_FILE
    echo "    http.HandleFunc(\"/js/db/$FILENAME.js\", func(w http.ResponseWriter, r *http.Request) {" >> $OUTPUT_FILE
    echo "        w.Header().Set(\"Content-Type\", \"application/javascript\")" >> $OUTPUT_FILE
    echo "        s := \`$CONTENT\`" >> $OUTPUT_FILE
    echo "        fmt.Fprint(w, s)" >> $OUTPUT_FILE
    echo "    })" >> $OUTPUT_FILE
    echo "}" >> $OUTPUT_FILE
done

echo "Go web handlers generated successfully!"
